import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/Themecontext"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
<<<<<<< HEAD
  title: "NextgenFolio AI - AI Portfolio Generator",
  description: "Transform your resume into a stunning portfolio website with AI",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 8704c0d2b0435dd392d86958e1c5065b0c1bc970
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        <ThemeProvider>
          {children}
        </ThemeProvider>
=======
        {children}
>>>>>>> 8704c0d2b0435dd392d86958e1c5065b0c1bc970
      </body>
    </html>
  );
}
